#!/bin/bash
#set -x # used in debugging
# Move a file from all subdirectories
# to a target directory.

# Creates the name for the log file
log="folderColapseLog_$(date '+%d%B%y|%I:%M')"

# User defined Variables
cd
echo "Run this script as sudo"
echo "Warning!! Do Not Put Target Directory Inside Source Directory"
echo -n "It will be deleted!! Press Enter to continue"
read
echo "Did you remember to back everything up first?"
echo -n "Press ctrl+c at any point to cancel"
read
echo -n "I'm serious, Devon. Back up your shit."
read
echo "Okay, here goes nothing"
echo "First, a couple questions:"
echo -n "Is everything unzipped? (Y/n) "
read unzip
echo -n "What is the source directory? "
read source
cd "$source"
echo -n "Where do you want the files?  "
read dest
log="$dest"/"$log" # tells the script where to put the log file

# scans and unzips files in the src dir
if [ $unzip == 'n' ] || [ $unzip == 'no' ]; then
	echo >> "$log".log;echo "Deleting files as they are unzipped." >> "$log".log
	find . -depth -name '*.zip' -exec /usr/bin/unzip -n {} \; -delete |& tee -a "$log".log
	echo "Unzipped files $(date '%I:%M')" >> "$log".log
	echo "Done. Starting program"
fi
echo "Alright, last two questions:"
echo "File types in '$source':"
find "$source" -type f -name "*"."*" | sed 's|.*\.||' | sort -u

# defines where to start the script when it restarts
function colapse
{
echo -n "What file types are we looking to move? "
read fileTypes
echo "Enter the mode you want to run this in:"
echo "	-i prompt before each instance of overwrite. You will be asked each time for a new name."
echo "	-f overwrite each instance automatically without prompting"
echo "	-n do not overwrite existing files"
echo -n "Mode: "
read mode
sleep 0.5
echo >> "$log".log; echo "Moving Files with $mode mode" >> "$log".log
find -iname "*.$fileTypes" -exec mv -v $mode '{}' "$dest" \; |& tee -a "$log".log
}

# Prompts to restart the script
function restart
{
echo "File types still in '$source':"
find "$source" -type f -name "*"."*" | sed 's|.*\.||' | sort -u
echo -n "Done, shall I restart? (Y/n) "
read restart
if [ $restart == 'n' ] || [ $restart == 'no' ];then
	echo -n "Want me to remove $source in it's entirety? (y/N) "
	read remove
	if [ $remove == 'y' ] || [ $remove == 'yes' ];then
		echo >> "$log".log;echo "Removing $source folder" >> "$log".log
		cd ..
		rm -rf "$source"
		exit
	else
		exit
	fi
else
	echo >> "$log".log;echo "Restarting Program" >> "$log".log
	colapse
	restart
fi
}

# This part kickstarts the whole thing
colapse
restart
