#!/bin/bash
# The first two while loops create an array using the user input (character name) and prints the message that goes with it.
# The following defines the function to parse out each message and type it out one character at a time.
# The function takes two arguments: The message to be typed out, and the time between each letter being typed
filename=$1
cd "$(dirname "$0")" # this command assigns the working directory to the one this file is in
cd ../../Scripts
date=$(date)
clear
echo
sleep 1
./writing "Call trans opt: received. $date REC:Log>" 0.05
sleep 2.5
echo
./writing "Trace program: running" 0.05
sleep 0.1
echo
echo "ChapterOne/Opening" > ../Saves/$filename.txt
echo "Name: $filename" >> ../Saves/$filename.txt
echo "Found on: $date" >> ../Saves/$filename.txt
echo "" >> ../Saves/$filename.txt
echo "Coordinates found: " >> ../Saves/$filename.txt
./startlocation 0.05 $filename
#sleep 0.5
./writing "$filename found" 0.05
sleep 2.5
clear

# The following begins the game after the filename has been found
Wakeup="Wake up, $filename"
clear
echo
./writing "$Wakeup" 0.05;./blinking  0.05
clear

# This clears the screen then slowly writes The Matrix has you
echo
./writing "The Matrix has you..." 0.25
sleep 5
clear
echo
./writing "Follow the white rabbit." 0.05
sleep 5
clear
echo
echo -n "Knock, knock, $filename."
sleep 5
echo
clear
sed -i "1s/.*/ChapterOne\/Cafe/" ../Saves/$filename.txt
echo "*" >> ../Saves/$filename.txt
echo "*" >> ../Saves/$filename.txt
../Chapters/ChapterOne/Cafe $filename 0.05
exit
